services:
  - type: web
    name: sql-ppt-api
    env: docker  # 👈 Switch from "python" to "docker"
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        value: sk-proj-6LMEydIrkDWXPWYNgLbqT3BlbkFJsEbRSsrjGUcglSq00vrNg
      - key: AUTOGEN_USE_DOCKER
        value: "False"
      - key: SQL_SERVER
        sync: false
      - key: SQL_DATABASE
        sync: false
      - key: SQL_UID
        sync: false
      - key: SQL_PASSWORD
        sync: false
